[package]
name = "crc32crust"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "crc32crust"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0"
crc32c = "0.6.0"
